<?php
DEFINE('STATUS_NO_ERROR', 0);
DEFINE('STATUS_ERROR_DATA', 1);
DEFINE('STATUS_ERROR_NAME', 2);
DEFINE('STATUS_ERROR_LVL', 3);
DEFINE('STATUS_ERROR_ID', 4);
DEFINE('FATAL_ERROR', 5);
DEFINE('STATUS_ERROR_CLASS_ID', 5);
DEFINE('STATUS_ERROR_CLASS_SKILL', 6);
DEFINE('STATUS_ERROR_SWITCH', 7);
DEFINE('STATUS_ERROR_CLASS_LVL', 8);

